'use client';

import { createClient } from '@/lib/supabase/client';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { ArrowLeft, Loader2, Tag, AlertCircle, Ticket, CheckCircle2, Copy } from 'lucide-react';
import Link from 'next/link';

const CATEGORIES = [
  'Hardware',
  'Software',
  'Network',
  'Email & Communication',
  'VPN & Remote Access',
  'Printer & Scanner',
  'Access & Permissions',
  'Other',
];

const PRIORITIES = [
  { value: 'low', label: 'Low', description: 'Minor issue, no immediate impact' },
  { value: 'medium', label: 'Medium', description: 'Normal priority issue' },
  { value: 'high', label: 'High', description: 'Urgent issue, affecting work' },
  { value: 'critical', label: 'Critical', description: 'Business-critical issue' },
];

export default function NewTicketPage() {
  const router = useRouter();
  const supabase = createClient();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [category, setCategory] = useState('');
  const [priority, setPriority] = useState('medium');
  
  // Success state - show ticket code
  const [createdTicket, setCreatedTicket] = useState<{
    id: string;
    ticket_code: string;
    title: string;
  } | null>(null);
  const [copied, setCopied] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!title.trim()) {
      setError('Please enter a title');
      return;
    }
    
    if (!description.trim()) {
      setError('Please enter a description');
      return;
    }

    if (!category) {
      setError('Please select a category');
      return;
    }

    if (title.length < 5) {
      setError('Title must be at least 5 characters');
      return;
    }
    
    if (description.length < 10) {
      setError('Description must be at least 10 characters');
      return;
    }

    setLoading(true);
    setError(null);

    try {
      // Get current user
      const { data: { user } } = await supabase.auth.getUser();
      
      if (!user) {
        router.push('/login');
        return;
      }

      // Get user profile with ticket_code
      const { data: profile } = await supabase
        .from('profiles')
        .select('organization_id, ticket_code, role')
        .eq('id', user.id)
        .single();

      if (!profile?.organization_id) {
        setError('You must belong to an organization to create tickets');
        return;
      }

      // Only customers (requesters) can create tickets
      if (profile.role !== 'requester') {
        setError('Only customers can create support tickets. Employees cannot create tickets.');
        return;
      }

      // Create ticket - ticket_code is auto-generated by DB trigger
      const { data: ticket, error: ticketError } = await supabase
        .from('tickets')
        .insert({
          title: title.trim(),
          description: description.trim(),
          category: category || null,
          priority: priority,
          organization_id: profile.organization_id,
          created_by: user.id,
          status: 'open',
        })
        .select()
        .single();

      if (ticketError) {
        setError(ticketError.message);
        return;
      }

      // If ticket_code is not returned from insert (trigger-generated), fetch it separately
      let ticketCode = ticket.ticket_code;
      if (!ticketCode) {
        const { data: refreshedTicket } = await supabase
          .from('tickets')
          .select('ticket_code')
          .eq('id', ticket.id)
          .single();
        ticketCode = refreshedTicket?.ticket_code || null;
      }

      // Log activity
      await supabase.from('ticket_activity_logs').insert({
        ticket_id: ticket.id,
        user_id: user.id,
        action: 'created',
        new_value: title,
      });

      // Store created ticket info for success display
      setCreatedTicket({
        id: ticket.id,
        ticket_code: ticketCode,
        title: ticket.title,
      });
      
    } catch {
      setError('An unexpected error occurred');
    } finally {
      setLoading(false);
    }
  };

  const copyTicketCode = () => {
    if (createdTicket?.ticket_code) {
      navigator.clipboard.writeText(createdTicket.ticket_code);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  // Show success state with ticket code
  if (createdTicket) {
    return (
      <div className="w-full max-w-lg sm:max-w-xl lg:max-w-2xl mx-auto space-y-4 sm:space-y-6">
        {/* Header */}
        <div className="flex items-center gap-2 sm:gap-4">
          <Link
            href="/dashboard/tickets"
            className="p-2 rounded-lg hover:bg-slate-100 transition-colors shrink-0"
          >
            <ArrowLeft className="w-4 h-4 sm:w-5 sm:h-5 text-slate-600" />
          </Link>
          <div>
            <h1 className="text-xl sm:text-2xl font-bold text-slate-900">Ticket Created!</h1>
            <p className="text-slate-600 mt-0.5 sm:mt-1 text-sm sm:text-base">
              Your support request has been submitted
            </p>
          </div>
        </div>

        {/* Success Message */}
        <div className="card">
          <div className="p-4 sm:p-6">
            <div className="flex items-start gap-3 sm:gap-4">
              <div className="w-10 h-10 sm:w-12 sm:h-12 rounded-full bg-green-100 flex items-center justify-center shrink-0">
                <CheckCircle2 className="w-5 h-5 sm:w-6 sm:h-6 text-green-500" />
              </div>
              <div className="flex-1 min-w-0">
                <h2 className="text-base sm:text-lg font-semibold text-slate-900">
                  {createdTicket.title}
                </h2>
                <p className="text-slate-600 mt-1 text-sm">
                  Your ticket has been created successfully. Our support team will review it shortly.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Ticket Code Display */}
        <div className="card">
          <div className="p-4 sm:p-6 border-b border-slate-200">
            <h3 className="font-semibold text-slate-900 text-sm sm:text-base">Ticket Code</h3>
            <p className="text-xs sm:text-sm text-slate-500 mt-1">
              Share this code with customers to let them create accounts
            </p>
          </div>
          <div className="p-4 sm:p-6">
            <div className="flex items-center gap-3">
              <div className="flex-1 p-3 sm:p-4 bg-slate-100 rounded-lg border border-slate-200">
                <div className="flex items-center justify-between gap-2">
                  <div className="flex items-center gap-2 sm:gap-3 min-w-0">
                    <Ticket className="w-4 h-4 sm:w-5 sm:h-5 text-primary shrink-0" />
                    <span className="font-mono text-lg sm:text-xl font-bold text-slate-900 truncate">
                      {createdTicket.ticket_code}
                    </span>
                  </div>
                  <button
                    onClick={copyTicketCode}
                    className="p-1.5 sm:p-2 hover:bg-slate-200 rounded-lg transition-colors shrink-0"
                    title="Copy to clipboard"
                  >
                    {copied ? (
                      <CheckCircle2 className="w-4 h-4 sm:w-5 sm:h-5 text-green-500" />
                    ) : (
                      <Copy className="w-4 h-4 sm:w-5 sm:h-5 text-slate-400" />
                    )}
                  </button>
                </div>
              </div>
            </div>
            <p className="text-xs text-slate-500 mt-2 sm:mt-3">
              Customers can use this code to sign up and track their support requests.
            </p>
          </div>
        </div>

        {/* Actions */}
        <div className="flex flex-col sm:flex-row justify-end gap-2 sm:gap-3">
          <Link
            href="/dashboard/tickets"
            className="btn-ghost justify-center"
          >
            Back to Tickets
          </Link>
          <Link
            href={`/dashboard/tickets/${createdTicket.id}`}
            className="btn-primary justify-center"
          >
            View Ticket
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="w-full max-w-lg sm:max-w-xl lg:max-w-2xl mx-auto space-y-4 sm:space-y-6">
      {/* Header */}
      <div className="flex items-center gap-2 sm:gap-4">
        <Link
          href="/dashboard/tickets"
          className="p-2 rounded-lg hover:bg-slate-100 transition-colors shrink-0"
        >
          <ArrowLeft className="w-4 h-4 sm:w-5 sm:h-5 text-slate-600" />
        </Link>
        <div>
          <h1 className="text-xl sm:text-2xl font-bold text-slate-900">Create New Ticket</h1>
          <p className="text-slate-600 mt-0.5 sm:mt-1 text-sm sm:text-base">
            Submit a new support request
          </p>
        </div>
      </div>

      {/* Form */}
      <form onSubmit={handleSubmit} className="card space-y-4 sm:space-y-6">
        {error && (
          <div className="p-3 sm:p-4 rounded-lg bg-red-50 border border-red-200 flex items-start gap-2 sm:gap-3">
            <AlertCircle className="w-4 h-4 sm:w-5 sm:h-5 text-red-500 shrink-0 mt-0.5" />
            <div>
              <p className="font-medium text-red-800 text-sm">Error</p>
              <p className="text-sm text-red-600">{error}</p>
            </div>
          </div>
        )}

        {/* Title */}
        <div className="space-y-1.5 sm:space-y-2">
          <label htmlFor="title" className="block text-sm font-medium text-slate-700">
            Title <span className="text-red-500">*</span>
          </label>
          <input
            id="title"
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="Brief description of the issue"
            className="input"
            disabled={loading}
          />
          <p className="text-xs text-slate-500">
            Minimum 5 characters
          </p>
        </div>

        {/* Category */}
        <div className="space-y-1.5 sm:space-y-2">
          <label htmlFor="category" className="block text-sm font-medium text-slate-700">
            Category <span className="text-red-500">*</span>
          </label>
          <div className="relative">
            <select
              id="category"
              value={category}
              onChange={(e) => setCategory(e.target.value)}
              className="input appearance-none pr-10"
              disabled={loading}
            >
              <option value="">Select a category</option>
              {CATEGORIES.map((cat) => (
                <option key={cat} value={cat}>
                  {cat}
                </option>
              ))}
            </select>
            <Tag className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400 pointer-events-none" />
          </div>
        </div>

        {/* Priority */}
        <div className="space-y-1.5 sm:space-y-2">
          <label className="block text-sm font-medium text-slate-700">
            Priority <span className="text-red-500">*</span>
          </label>
          <div className="grid grid-cols-2 sm:grid-cols-2 lg:grid-cols-4 gap-2 sm:gap-3">
            {PRIORITIES.map((p) => (
              <button
                key={p.value}
                type="button"
                onClick={() => setPriority(p.value)}
                disabled={loading}
                className={`p-2.5 sm:p-3 rounded-lg border-2 text-left transition-all ${
                  priority === p.value
                    ? 'border-primary bg-primary/5'
                    : 'border-slate-200 hover:border-slate-300'
                } disabled:opacity-50`}
              >
                <p className="font-medium text-slate-900 text-sm">{p.label}</p>
                <p className="text-xs text-slate-500 mt-0.5 line-clamp-2">{p.description}</p>
              </button>
            ))}
          </div>
        </div>

        {/* Description */}
        <div className="space-y-1.5 sm:space-y-2">
          <label htmlFor="description" className="block text-sm font-medium text-slate-700">
            Description <span className="text-red-500">*</span>
          </label>
          <textarea
            id="description"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="Please provide detailed information about the issue..."
            rows={5}
            minLength={10}
            className="input resize-y min-h-[120px] sm:min-h-[150px]"
            disabled={loading}
          />
          <p className="text-xs text-slate-500">
            Minimum 10 characters. Include steps to reproduce if applicable.
          </p>
        </div>

        {/* Actions */}
        <div className="flex flex-col sm:flex-row justify-end gap-2 sm:gap-3 pt-3 sm:pt-4 border-t border-slate-200">
          <Link
            href="/dashboard/tickets"
            className="btn-ghost justify-center"
            type="button"
          >
            Cancel
          </Link>
          <button
            type="submit"
            disabled={loading}
            className="btn-primary justify-center"
          >
            {loading ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                <span className="hidden sm:inline">Creating...</span>
                <span className="sm:hidden">...</span>
              </>
            ) : (
              'Create Ticket'
            )}
          </button>
        </div>
      </form>
    </div>
  );
}

